### ISSUE TITLE
The ability to login to your user account

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#2]
As a website user, I want to be able to login to my account after signing up using the login screen. By logging in, this will give me the ability to upload new recipes to the website for other people to access.

Constraints:
- Login page must require username and password
    - Username should match a record in database
    - Password should match corresponding username in database
- The page should contain a forgot password button to enable them to reset their password on a separate page.

Acceptance Criteria:
1. forgot password button must be located on the login page
2. login button must be located on the login page
3. the password field should hide the the password by default
4. have a warning/flag, if the password does not match the username
5. have a warning/flag, if any of the fields are left blank when the user tries to submit
6. password needs to be transferred/compared securely

Tasks:
- [x] Isam - backend: create a function that checks if a password matches a username which already exists in the database
- [x] Ryan/Abdullah - backend: create a function to decrypt password before comparing with password in database
- [x] Ryan/Abdullah - frontend/backend: create a function to encrypt password before sending to backend
- [x] Ryan/Brendan - frontend: Initialize session variable after user successfully logs in
- [x] Isam/Abdullah - frontend: redirect to blank view-profile page after successful login and alert (with redirect delay)
- [x] Mallory - frontend: show a success message once the user successfully logs in
- [x] Mallory - frontend: show the flags for acceptance criteria 4, 5
- [x] Mallory - frontend: redirect to forgot password reset page when clicking on the password reset button
- [x] Abdullah - frontend: Create input fields to display to user and prompt for username/password on webpage
- [x] Ryan - frontend: connect to the backend to make sure every function works

**Comment by bdk99** [comment]
As a website user, I want to be able to login to my account after signing up using the login screen. By logging in, this will give me the ability to upload new recipes to the website for other people to access.

Constraints:
- Login page must require username and password
    - Username should match a record in database
    - Password should match corresponding username in database
- The page should contain a forgot password button to enable them to reset their password on a separate page.


Acceptance Criteria:
1. forgot password button must be located on the login page
2. login button must be located on the login page
3. the password field should hide the the password by default
4. have a warning/flag, if the password does not match the username
5. have a warning/flag, if any of the fields are left blank when the user tries to submit
6. password needs to be transferred/compared securely


Tasks:
- [ ] backend: create a function that checks if a password matches a username which already exists in the database
- [ ] frontend/backend: create a function to encrypt password before sending to backend
- [ ] frontend: redirect to blank view-profile page after successful login and alert (with redirect delay)
- [ ] frontend: connect to the backend to make sure every function works
- [ ] frontend: show a success message once the user successfully logs in
- [ ] frontend: show the flags for acceptance criteria 4, 5
- [ ] frontend: redirect to blank password reset page

**Comment by sjiang1** [comment]
Will the "forgot password button" on the login page work? If not, you can remove it from the acceptance criteria. If yes, please clarify the acceptance criteria.

Add the following criteria:
* Once the user logs in, if the user opens a new tab with a website URL, the tab should also consider the user as logged in.
* If the user enters the correct username/password, there will be a message (or a webpage) to show that the user has logged in.
