### ISSUE TITLE
The ability to sign up and create a profile.

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2022Winter/capstone-gigabites#3]
As a website user, I want to be able to create an account using a username, a password, a security question/answer so that I can log in later and create recipes.

constraints:
- the username should be unique for each user
- the password should be strong (define a criteria for "strong")
       - At least 8 characters: the more characters, the better.
       - A mixture of both uppercase and lowercase letters.
       - A mixture of letters and numbers.
       - Inclusion of at least one special character, e.g., ! @ # ? ] 
         *Note*: do not use < or > in your password, as both can cause problems in Web browsers.

- the user should be able to write a security question and provide an answer when sign up.

Acceptance Criteria:

1. when the user provides valid values to all the fields in the sign up form, and click the sign up button, a sign up success message will be shown to the user to indicate the account is created.
2. the password field should hide the the password by default
3. have a flag when the user tries to use an existing user name
4. have a flag when the user tries to use a password that doesn't meet the "strong" criteria
5. have a warning/flag, if any of the fields left blank when the user tries to submit
6. password needs to be stored/transferred securely

Tasks:

- [x] Brendan - db: create a database/table to store the username/password/security 
- [x] Megan - backend: create a function that checks if a username exists in the database
- [x] Brendan - backend: create a function that adds the user to the database
- [x] Isam - frontend: connect to the backend to make sure every function works
- [x] Megan/Brendan - frontend: create the front-end of the sign up page (text fields, buttons, etc.) so that the user can type username/password/security question/answer on the page
- [x] Brendan - frontend: show the flags for acceptance criteria 3, 4, and 5
- [x] Isam - frontend: show the success message once the user successfully signs up
- [x] Megan - backend: Add prefilled Bio when a user signs-up that will be automatically populated in the database.
- [x] Megan - backend: Add prefilled profile picture when a user signs-up that will be automatically populated in the database.

**Comment by bdk99** [comment]
Task to add to this issue: 
- [ ] backend: Add prefilled Bio when a user signs-up that will be automatically populated in the database.
