### ISSUE TITLE
The ability to view your profile if signed in

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#4]
As a website user I want the ability to view my profile after I sign in successfully using the login page.

Constraints:
-The user must be signed in to view their profile

Acceptance Criteria:
1. Displays username, profile picture and bio on page.
2. have a warning/flag, if the user is not logged in when trying to load the view profile page
3. User needs to be able to logout using the logout button located on the view profile screen
4. The page has a button that redirects the user to the create a new recipe page
5. The URL for each profile will be unique based on the profile's username

Tasks:
- [x] Brendan/Ryan - frontend: Create flags for acceptance criteria 2 and 3
- [x] Brendan/Ryan - frontend/backend: Change URL based on user's username
- [x] Brendan/Ryan - frontend: Create logout button with full functionality (end user session and redirect to home page)
- [x] Ryan/Brendan - frontend: Add buttons (x2) to redirect to followers/following page (and display the corresponding number inside the button) and redirect to corresponding blank pages.
- [x] Mallory - frontend: Create button to redirect to create-recipe page to add a new recipe as the logged in user
- [x] Mallory - frontend: Create edit profile button with redirect to edit profile page
- [x] Mallory - frontend: Display recipe feed areas which contain recipe names, image ~~and username of user that uploaded recipe~~
- [x] Brendan/Mallory - frontend: Display username, profile picture and bio on page
- [x] Mallory - frontend: connect to the backend to make sure every function works

**Comment by bdk99** [comment]
Please see navigation bar PBI for creating and adding logout button with full functionality. (Task number 3)
Please see https://github.com/COSC481W-2022Winter/capstone-gigabites/pull/20 for the individual pull request completing this task.

This task was also completed using pull request https://github.com/COSC481W-2022Winter/capstone-gigabites/pull/21 as these session variables are needed to create flags/alerts on view-profile page when user is not logged in.

**Comment by sjiang1** [comment]
~~LOL. next time, please create a new PBI/issue.~~
Please ignore this.
