### ISSUE TITLE
Modifications to the upload recipe page and recipe schema/model

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#42]
As a user I would like to have additional options on the upload a recipe page

Constraints:
- Minimum of one non-zero time on user input (pertaining to bake time, cook time, prep time) .

Acceptance Criteria:
1. Page must prompt user for the following information:
    a. Cook time
    b. Amount per serving
    c. Units for Amount per serving
    d. Units for bake time
    e. Units for cook time
    f.  Units for prep time
2. Remove unnecessary input field for total time

Tasks:
- [x] Abdullah - frontend: Add logged in user's username to upload recipe function
- [x] Abdullah - frontend: Add units to upload recipe page for bake time, cook time, prep time
- [x] Mallory - frontend: Redirect to view recipe page and display success message on successful recipe upload
- [x] Abdullah - frontend: Fix Ingredients on upload recipe
     - Remove ingredients label from directions textbox
- [x] Mallory - frontend: Create flags/warning for fields in acceptance criteria b, c, and time if total time is zero
- [x] Mallory - frontend: Create function to ensure total time is non-zero
- [x] Mallory/Abdullah - frontend: Edit current create a recipe page with the following:
     - Add additional field for cook time
     - Add additional field for amount per serving
     - Add dropdown field for units of amount per serving
     - Remove total time input field.
     - Units for bake time
     - Units for cook time
     - Units for prep time
- [x] Abdullah - backend: Update the following in the recipe schema/model , and add cook time to total time function
     - Default recipe image
     - Username
     - Cook time
     - Amount per serving
     - Units for Amount per serving
     - Units for bake time
     - Units for cook time
     - Units for prep time
- [x] Abdullah/Ryan - frontend: Upload an image for the recipe

**Comment by sjiang1** [comment]
Just to double-check, this PBI is in Sprint 4 because Mallory still needs to redirect to view recipe page, right?
