### ISSUE TITLE
The ability to explore the website using an explore page

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#71]
As a website user I would like the ability to explore different recipes on the website using the explore page.

Constraints:
- The user does not have to be logged in, in order to view the explore page.
- Page should be styled professionally

Acceptance Criteria:
1. Explore page must display a maximum of 10 results with the following information:
    a. Recipe Name
    b. Recipe Image
    c. Recipe Description
    d. User who uploaded recipe for each recipe 
2. Explore page must be accessible on the Navbar.
3. The explore page must display the 10 most recently updated/uploaded recipes.

Tasks:
- [x] Mallory - backend: Add date to recipe model with default date/time value.
- [x] Mallory - frontend: Create explore page:
- - [x] Create section with border for newest recipes.
- - [x] Recipes on the explore page must be located in a table.  Each recipe must contain everything in acceptance criteria 1, 3
- [x] Mallory - frontend: Add explore page button (with label Explore) to Navbar.
- [x] Mallory - frontend: Add route for explore page in App.js

**Comment by sjiang1** [comment]
Add an acceptance criterion: The explore page must display the 10 most recently updated/uploaded recipes.
