### ISSUE TITLE
The ability to search for recipes based on recipe title or recipes that a user uploaded

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#72]
As a website user I would like the ability to search recipes based on recipe names, or recipes based on the user who uploaded them on the home page.

Constraints:
- Search can only contain a maximum of 100 characters
- Search must have a minimum of 3 characters

Acceptance Criteria:
1. Search must be able to find recipes based on partial names.
2. Search must display all search results
3. Search page must contain dropdown to determine if search is based on recipe name or username.
4. Search results page must contain recipe image, recipe name, recipe description and the username who uploaded the recipe on the page.
5. User should be able to view the recipe page by clicking on the name of the recipe.

Tasks:
- [x] Abdullah - frontend: Create search bar located on the home page with a dropdown, and search button to satisfy acceptance criteria 3.
- [x] Abdullah - backend: Create backend function to query recipe collection in database for recipes and forward user to search results page.  Task must satisfy acceptance criteria 1
- [x] Abdullah - frontend: Create table with data from backend on search results page to satisfy acceptance criteria 2, 4
- [x] Abdullah - frontend: Redirect user to recipe page based on acceptance criteria 5.

**Comment by sjiang1** [comment]
Will this overlap with issue #73?
