### ISSUE TITLE
The ability to reset a users forgotten password using their username and email address

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#74]
As a website user I would like the ability to reset my forgotten password using the forgot password button on the login page.

Constraints:
- Forgot password page must be professionally styled
- Password reset page must be professionally styled

Acceptance Criteria:
1. After clicking forgot password on the Login page, redirect to forgot password page
2. Forgot password page must prompt user for username
3. Forgot password page must have fully functional submit button that redirects to password reset page and sends recovery code to specified users email
4. Password reset page will prompt user for username, recovery code and new password on page
5. Password reset page has fully functional submit button that resets the users password based on matching recovery code, and redirects to the login page. 

Tasks:
- [x] Ryan/Brendan - frontend: Create routes for forgot password and password reset
- [x] Ryan/Brendan - frontend: Create password reset page to satisfy acceptance criteria 4 and 5
- [x] Ryan/Brendan - frontend: Create forgot password page to satisfy acceptance criteria 2 and 3
- [x] Ryan/Brendan - frontend: On submission of the forgot password page, send user specified username to backend function.
- [x] Ryan/Brendan - backend: Create function to accept user specified username from frontend, and query for the users email, and recovery code.
- [x] Ryan/Brendan - backend: Add randomly generated user recovery code to user schema/model using Math.random
- [x] Ryan/Brendan - backend: Send email to user containing user's name and recovery code and the name of the website.

**Comment by sjiang1** [comment]
'Ryan/Brendan - frontend: Create password reset page to satisfy acceptance criteria 2 and 3' --> forgot password page?
'Ryan/Brendan - frontend: Create forgot password page to satisfy acceptance criteria 4 and 5' --> password reset page?
