### ISSUE TITLE
The ability to edit/delete recipes that I created

### ISSUE THREAD

**Issue by bdk99** [COSC481W-2022Winter/capstone-gigabites#75]
As a website user I would like the ability to edit and delete recipes that I created.

Constraints:
- User must be logged in to edit/delete their own recipes

Acceptance Criteria:
1. The following recipe information must be filled in before allowing the user to submit the recipe (except letter g):
    a. Recipe name
    b. Recipe description
    c. Directions for creating recipe
    d. Ingredients to create the recipe
-       Ingredient Name
         Ingredient Measurement
         Ingredient Units 
    e. Prep time
    f. Serving Size
    g. The ability to upload an image for the recipe
    h. Cook time
    i. Bake time
    j. Amount per serving
    k. Units for Amount per serving
    l. Units for bake time
    m. Units for cook time
    n. Units for prep time
2. Redirect to view-recipe page on successful recipe edit
3. Redirect to Explore page on deletion of a recipe.
4. Page must contain recipe delete button on edit recipe page
5. Recipe information must be pre-populated from the recipe collection in the database
6. The page must not override the original image if they don't update it.

Tasks:
- [x] Megan - frontend: Create edit recipe page based on acceptance criteria 1 and pre fill with information to satisfy acceptance criteria 5.
- [x] Megan - frontend: Add routing to edit recipe page (recipe/edit/:id) in App.js
- [x] Megan - frontend: Create submit button on page with fully functionality 
- [x] ~~Isam~~ Brendan - frontend : Create delete button on page with fully functionality (Acceptance Criteria 4)
- [x] Megan - backend: Create function to update recipe information based on frontend post method when editing recipe and on successful edit redirect them to view-recipe page (to satisfy acceptance criteria 2) 
- [x] ~~Isam~~ Brendan - backend: Create function to delete recipe and then redirect user from backend to explore page (Satisfies acceptance criteria 3)

**Comment by sjiang1** [comment]
`Brendan - frontend: connect to the backend to make sure every function works` This has been a very tricky task. What functions do you refer to? The backend functions or the website functions in general?
